# Numpy - Mathematical statistics

In [1]:
import numpy as np

In [3]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [4]:
c = np.array([2, 3, 4, 5, 6, 2]).reshape(2, 3)
c

array([[2, 3, 4],
       [5, 6, 2]])

In [5]:
d = np.array([2, 3, 4, 5, 6, 3, 2, 5]).reshape(2, 2, 2)
d

array([[[2, 3],
        [4, 5]],

       [[6, 3],
        [2, 5]]])

In [6]:
e = np.array([1, 2, 3, 4, 5, 6])
print(e.sum()) # Sum of the array
print(e.min()) # Find the minimum value in the array
print(e.max()) # Find the maximum value in the array
print(e.mean()) # Find the mean of the array

21
1
6
3.5


In [7]:
np.zeros(5) # Creates and array of zeros with 5 elements
np.linspace(0, 6, 10) # Creates an array of values from 0 through 6 in 10 even spaces
np.random.rand(3) # Three random values between 0 and 1
np.random.randint(1, 1000) # A random integer between 1 and 1000
np.arange(25) # Like the "range" function, this give you a range of integers between 1 & 25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.linspace(0, 6, 10)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [10]:
np.random.rand(3)

array([0.56059155, 0.88386146, 0.76960143])

In [11]:
np.random.randint(1, 1000)

998

In [12]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])